compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistryServer: "https://mirrors.cloud.tencent.com/npm/"

yarnPath: .yarn/releases/yarn-4.8.0.cjs
